Header
Tasitaforme/healthy-way pull request #16
Opened 2023-12-19 22:37 UTC by NellyOgo

Сделано статический Header 
*без модальных окон

2023-12-19 22:46 UTC, Tasitaforme requested changes
Завантажено 37 картинок, видали все, що стосується твого хедер. Аватарка вже є в папці images. Всі іконки є в sprite.svg - витягти їх з нього. Завантажені нові бібліотеки, які ти не використовувала - видали все зайве.

2023-12-20 23:11 UTC, NellyOgo commented
Фото лишние удалила
Зависимости удалила
Добавлена работа по модалкам

2023-12-20 23:22 UTC, Tasitaforme requested changes
profile-circle.png видали і заміни її на іконку зі спрайту

2023-12-20 23:28 UTC, NellyOgo commented
На текущий момент png нужен. Предлагаю принять реквест, т.к. для следующих шагов в доработке модалки нужны последние обновления сделаннве в проекте. В новой ветке учту рекомендации

2023-12-20 23:44 UTC, Tasitaforme approved these changes

2023-12-20 23:44 UTC, merged